# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
cache: packages
apt_packages:
  - libudunits2-dev
warnings_are_errors: false
r_github_packages: hadley/devtools
